### ISSUE TITLE
is there a wrong in line 114?

### ISSUE THREAD

**Issue by sun-sc** [Jays-code-collection/HMMs_Stock_Market#7]
` previous_data_start_index = max(0, day_index - self.n_latency_days)
previous_data_end_index = max(0, day_index - 1)
previous_data = self.test_data.iloc[previous_data_end_index: previous_data_start_index]`
**previous_data_start_index**  is smaller than **previous_data_end_index** , so **test_data.iloc[previous_data_end_index: previous_data_start_index]** will be empty?

**Comment by Jays-code-collection** [comment]
That's embarrassing, I had fixed that locally as I had swapped the two round for testing and I must have commited the wrong version a while ago! I'll fix that now.
