### ISSUE TITLE
i want to ask about the Accuracy about the model

### ISSUE THREAD

**Issue by sun-sc** [Jays-code-collection/HMMs_Stock_Market#8]
when i use this model, i got the accuracy about 50%( 31 true in 60 prediction). I want to ask about the accuracy about your test.
thanks~(maybe there are some wrong on my environment so that i can't use the code directly)

**Comment by Jays-code-collection** [comment]
Hey, could I ask how long did you train the model for and how were you  classifying your accuracy? Were you going for rounded exact numbers or just whether it had accurately predicted upwards or downwards movement?
